aplications/calculadora_Experiencia/urls.py
from django.urls import path
from . import views

app_name = 'calculadora'

urlpatterns = [
    path('welcome-experience/', views.welcome, name = 'welcome' ),
    path('validate-experience/', views.validar_experiencia, name = 'validar-experiencia' ),  
]

aplications/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.Home.as_view(), name = 'home' ),
]

tools_contratacion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('aplications.calculadora_Experiencia.urls')),
    path('',include('aplications.home.urls')),
    path('',include('aplications.tabla_honorarios.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/nav.html
{% load static %}



<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home:home' %}">Contratación Tools</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'calculadora:welcome' %}">Calculadora de Experiencia</a>
                </li>
                <!-- Agregar más elementos de menú según tus necesidades -->
            </ul>
        </div>
    </div>
</nav>